version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: auth-service_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: 12345678

    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

# networks:
#   internal-network:
#     driver: bridge