server:
  port: 8084

spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5435/auth_db
    username: artem
    password: 12345678
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-changelog.yaml

jwt:
  secretAccess: "jhkfs12312kbjglj7823124gjhws7878dtSSJLHFSDYUFSDALJHWERNLBASDFG"
  secretRefresh: "jhkkjhxdfgksjdhffs12312kbjglj7823124gjhws7878dtSSJLHFSDYUFSDALJHWERNLBASDFG"
  expirationAccess: 360000 # 1 час
  expirationRefresh: 259200000 # 1 месяц

business-service:
  base-url: http://localhost:8083/
